# Generated by Django 4.1.2 on 2022-10-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0004_alter_user_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
    ]
