# Generated by Django 4.1.2 on 2022-10-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0005_remove_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, default='2022-10-31'),
            preserve_default=False,
        ),
    ]
